General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 50
    grad_acc: 2
    frozen_bn: False
    patience: 20
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: bisque_data
    data_shuffle: True
    data_dir: Camelyon16/pt_files/
    label_dir: dataset_csv/camelyon16/
    fold: 0
    nfold: 4

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 2


Optimizer:
    opt: lookahead_radam
    lr: 0.01
    opt_eps: null 
    opt_betas: null
    momentum: 0.9
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

