General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 1000
    grad_acc: 2
    frozen_bn: False
    patience: 20
    server: train
    log_path: logs/
    grad_clip_val: 0.5

Data:
    dataset_name: camel_data
    data_shuffle: True
    data_dir: ./../BISQUE_BREAST_NORMALIZED/pt_files/
    label_dir: ./../BISQUE_BREAST_NORMALIZED/
    fold: 0
    nfold: 4

    train_dataloader:
        batch_size: 1
        num_workers: 2

    test_dataloader:
        batch_size: 1
        num_workers: 2

Model:
    name: TransMIL
    n_classes: 2

Optimizer:
    opt: lookahead_radam
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.00001
    lr_scheduler: ReduceLROnPlateau
    scheduler_patience: 5
    scheduler_factor: 0.5

Loss:
    base_loss: CrossEntropyLoss
